Semantic-Society/Neologism

- frontend/api/server/publications.ts
- frontend/src/app/home-dashboard/home-dashboard.component.html
- frontend/src/app/home-dashboard/home-dashboard.component.ts
- frontend/src/app/services/vocabularies.service.ts
filled username placeholder in left sidebar in home dashboard
adapted mongo query in graph component
> fixed bug due to Missing data

- frontend/src/app/home-dashboard/vocabulary-list/vocabulary-list.component.html
- frontend/src/app/home-dashboard/vocabulary-list/vocabulary-list.component.ts
removed multi subscriptions causing empty data override
> removed multi subscriptions causing empty data override

- frontend/src/app/home-dashboard/home-dashboard.component.html
- frontend/src/app/home-dashboard/home-dashboard.component.ts
updated timeout with Meteor.Tracker for data update
> Investigate for undefined data for loggedIn user

- frontend/.gitignore
- frontend/api/.gitignore
- frontend/api/package-lock.json
- frontend/src/app/home-dashboard/create-vocab-modal/create-vocab-modal.component.html
- frontend/src/app/home-dashboard/create-vocab-modal/create-vocab-modal.component.ts
- frontend/src/app/home-dashboard/home-dashboard.component.ts
suppressed error empty name
removed description default text
updated package-lock and .gitignore
added autocomplete to URI with class name in lowercase
> PR:ISSUE:62,69

- frontend/api/server/methods.ts
unable to import the module with typescript import. Replaced ECMAScript module import
> Unable to import module simple:json-routes

- frontend/api/server/methods.ts
- frontend/src/app/home-dashboard/home-dashboard.component.ts
- frontend/src/app/services/vocabularies.service.ts
1. adapted vocabulary create with
generated Id since no return value
due to meteor latency compensation
from call methods
2. route redirect using newly generated
vocab id
> UX enhancement - guiding user to vocabulary editor

- frontend/src/app/home-dashboard/create-vocab-modal/create-vocab-modal.component.ts
- frontend/src/app/home-dashboard/home-dashboard.component.ts
- frontend/src/app/services/vocabularies.service.ts
1. adapted method parameters for the unused component
2. compliance review
> Solved: Bug due to unused component parameter mismatch not caught while in dev mode

- frontend/api/models.ts
- frontend/api/server/methods.ts
- frontend/api/server/publications.ts
- frontend/src/app/app.module.ts
- frontend/src/app/home-dashboard/vocabulary-list/vocabulary-list.component.html
- frontend/src/app/home-dashboard/vocabulary-list/vocabulary-list.component.ts
- frontend/src/app/services/access-management.service.ts
- frontend/src/app/vocablist/components/remove-user-modal/remove-user-modal.component.html
- frontend/src/app/vocablist/components/remove-user-modal/remove-user-modal.component.scss
- frontend/src/app/vocablist/components/remove-user-modal/remove-user-modal.component.ts
1. solved bug for duplicate contributors while adding to the vocabulary
2. remove func for managing contrib
3. schema change for creator vs contrib
4. rdf now produce triples for creator and contrib separately
> Handle duplicate Contributors + Manage vocab contributors

- frontend/src/app/home-dashboard/vocabulary-list/vocabulary-list.component.ts
- frontend/src/app/vocablist/components/remove-user-modal/remove-user-modal.component.ts
> Auto imports went wrong. 

- frontend/src/app/editbox/editbox.component.css
- frontend/src/app/editbox/editbox.component.html
- frontend/src/app/editbox/editbox.component.ts
- frontend/src/app/mxgraph/mxgraph.component.html
1. make class name styling indicating editable in edit mode
2. autocomplete in the URI input
3. remove 'Add Recommended Properties'
4. hide complete section properties leaving, creating a button for property add
> Improve Usability of Class Form Editor

- frontend/api/server/methods.ts
- frontend/src/app/app.module.ts
- frontend/src/app/metadata/metadata.component.html
- frontend/src/app/mxgraph/mxgraph.component.ts
- frontend/src/app/mxgraph/property-model/property-edit.component.html
- frontend/src/app/mxgraph/property-model/property-edit.component.ts
- frontend/src/app/services/state-services/sidebar-state.service.ts
added component for prop del and edit
added support for multi edit of prop
> Property edit+delete

- frontend/api/server/methods.ts
- frontend/src/app/editbox/editbox.component.html
- frontend/src/app/editbox/editbox.component.ts
- frontend/src/app/editbox/editbox.service.ts
- frontend/src/app/services/vocabularies.service.ts
in the graph editor, upon selecting a node now user can delete the selected node/class clicking the button on top right corner
> delete class implemented

- frontend/src/app/editbox/editbox.component.css
- frontend/src/app/editbox/editbox.component.html
- frontend/src/app/editbox/editbox.component.ts
- frontend/src/app/mxgraph/mxgraph.component.ts
- frontend/src/app/mxgraph/property-model/property-edit.component.html
full width for URI input field
delete button for class location changed
colour scheme adapted for buttons
added URI completion to prop form
improved UX for prop editor
> UI/UX Improvements

- frontend/src/app/metadata/metadata.component.css
- frontend/src/app/metadata/metadata.component.html
- frontend/src/app/sidebar-editors/node-creator/node-creator.html
> Added Labels to default side bar data + autocomplete effect updated to keyup

- frontend/package-lock.json
- frontend/package.json
- frontend/src/app/home-dashboard/create-vocab-modal/create-vocab-modal.component.html
- frontend/src/app/home-dashboard/create-vocab-modal/create-vocab-modal.component.scss
- frontend/src/app/home-dashboard/create-vocab-modal/create-vocab-modal.component.ts
- frontend/src/app/home-dashboard/home-dashboard.component.ts
Update UI/UX for creating vocab form
> create vocab form UI/UX updates

- frontend/api/server/methods.ts
- frontend/src/app/editbox/editbox.component.html
- frontend/src/app/editbox/editbox.component.ts
fixed class name update bug (methods.ts)
code refactor editbox.component
> removed extra char causing update method failure

- frontend/src/app/mxgraph/mxgraph.component.css
- frontend/src/app/mxgraph/mxgraph.component.html
Also fixed a bug with empty canvas dialog. it used to appear at the bottom of the page even it is not open
> fixed side bar layout align

- frontend/src/app/mxgraph/mxgraph.component.html
- frontend/src/app/mxgraph/mxgraph.component.ts
added zoom in out controls with func
> added zoom in out controls with func

- app/src/app/core/node-creator.component.ts
- app/src/app/core/node-creator.css
- app/src/app/core/node-creator.html
- app/src/app/editbox/editbox.component.css
- app/src/app/editbox/editbox.component.html
- app/src/app/editbox/editbox.component.ts
- app/src/app/home-dashboard/home-dashboard.component.html
- app/src/app/metadata/metadata.component.css
- app/src/app/metadata/metadata.component.html
- app/src/app/mxgraph/mxgraph.component.css
- app/src/app/mxgraph/mxgraph.component.html
- app/src/app/mxgraph/standardView/standardView.component.html
- app/src/styles.css
CSS rules updated
removed most of the unused CSS rules
added cs rules
changed HTML layout
fixed IRI prefix bug
> Change mat theme to ant for graph component

- Dockerfile
Generate package-lock.json during Docker build
> Add npm install step to fix build pipeline

- .gitignore
- Dockerfile
- app/api/package-lock.json
- app/package-lock.json
- docker/package-lock.json
- package-lock.json
> 174 restore package lock

- app/src/app/batchRecommender/batchRecommender.component.html
- app/src/app/batchRecommender/batchRecommender.component.ts
- app/src/app/metadata/metadata.component.html
- app/src/app/metadata/metadata.component.ts
- app/src/app/mxgraph/mxgraph.component.html
- app/src/app/mxgraph/mxgraph.component.ts
- app/src/app/services/recommendation.service.ts
Merge remote-tracking branch 'origin/feature/ticket-161+165_loading+regulation' into merge-168-167
@enisze Merging feature/ticket-150_domain_location already up to date with HEAD
> Merged PR 167 and 168

- _config.yml
Based on https://nicolas-van.github.io/easy-markdown-to-github-pages/
> Add pages website

- app/src/app/core/node-creator.component.ts
- app/src/app/home-dashboard/vocabulary-list/vocabulary-list.component.ts
- app/src/app/services/vocabularies.service.ts
> Fixed typo and added alert message on publish success

- app/src/app/app.module.ts
- app/src/app/home-dashboard/vocabulary-list/vocabulary-list.component.html
- app/src/app/home-dashboard/vocabulary-list/vocabulary-list.component.ts
- app/src/app/services/vocabularies.service.ts
- link routing to vocab name and removed edit vocab btn
- improved CSS for vocab table (header padding and removed hover effect on action buttons)
-  refactor
- -reported bug for tooltip using todo
> removed btn and added anchor with editor

- app/src/app/editbox/editbox.component.ts
- app/src/app/home-dashboard/vocabulary-list/vocabulary-list.component.ts
- app/src/app/mxgraph/mxgraph.ts
- app/src/app/services/vocabularies.service.ts
- app/src/app/vocabulary-editor/mx-graph-editor/mx-graph-editor.component.ts
- app/src/app/vocabulary-editor/vocabulary-editor.component.ts
> Fix unwanted editbox open on mousedown

- app/api/server/methods.ts
- app/api/server/publications.ts
- app/src/app/app.module.ts
- app/src/app/core/node-creator.component.ts
- app/src/app/editbox/editbox.component.html
- app/src/app/editbox/editbox.component.ts
- app/src/app/editbox/editbox.service.ts
- app/src/app/home-dashboard/create-vocab-modal/create-vocab-modal.component.html
- app/src/app/home-dashboard/create-vocab-modal/create-vocab-modal.component.ts
- app/src/app/home-dashboard/home-dashboard.component.html
- app/src/app/home-dashboard/home-dashboard.component.scss
- app/src/app/home-dashboard/home-dashboard.component.ts
- app/src/app/mxgraph/N3Codec.ts
- app/src/app/mxgraph/mxgraph.component.html
- app/src/app/ng-zorro.module.ts
- app/src/app/rdf-uploader/rdf-uploader.component.spec.ts
- app/src/app/rdf-uploader/rdf-uploader.component.ts
- app/src/app/recommender/recommender.component.ts
- app/src/app/services/vocabularies.service.ts
- app/src/app/vocabulary-editor/vocabulary-editor.component.ts
> Add import from ttl rdf

- app/src/app/editbox/editbox.component.ts
- app/src/app/services/vocabularies.service.ts
- app/src/app/vocabulary-editor/edit.component.service.ts
- app/src/app/vocabulary-editor/mx-graph-editor/mx-graph-editor.component.ts
- app/src/app/vocabulary-editor/vocabulary-editor.component.ts
> Double-check open #184 comments with Hussain
